#!/usr/bin/env bash
# Deploy SamparkAI to the AWS VM from a checkout on this machine.
#
#   deploy/samparkai/deploy.sh ubuntu@<ec2-address> [path/to/EuphoriaKey.pem]
#
# Ships exactly what is committed (git archive of HEAD: no venv, no data, no
# keys), generates deploy/samparkai/.env on the box with a fresh API token the
# first time and prints it only on that run, adds the SamparkAI site to the
# host Caddy that already fronts the box, then builds and starts the app.
# Re-running redeploys the current HEAD and keeps the existing .env and data
# volume.
set -euo pipefail

TARGET=${1:?usage: deploy.sh user@host [key.pem]}
KEY=${2:-EuphoriaKey.pem}
REMOTE_DIR=/opt/samparkai

cd "$(git rev-parse --show-toplevel)"
SSH=(ssh -i "$KEY" -o StrictHostKeyChecking=accept-new "$TARGET")

echo "==> preparing $REMOTE_DIR on $TARGET"
"${SSH[@]}" "sudo mkdir -p $REMOTE_DIR && sudo chown \"\$USER\" $REMOTE_DIR"

echo "==> shipping $(git rev-parse --short HEAD)"
git archive --format=tar HEAD | "${SSH[@]}" "tar -x -C $REMOTE_DIR"

echo "==> configuring and starting"
"${SSH[@]}" bash -s <<'REMOTE'
set -euo pipefail
cd /opt/samparkai/deploy/samparkai

# Whether this run created the token. That is the only run that may print it.
FRESH_TOKEN=no

if [ ! -f .env ]; then
  FRESH_TOKEN=yes
  TOKEN=$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))' 2>/dev/null \
          || openssl rand -hex 32)
  cat > .env <<ENV
# Generated by deploy.sh. Runtime configuration for the SamparkAI container.
VAANI_ENV=prod
VAANI_API_TOKEN=$TOKEN
VAANI_LOG_LEVEL=INFO
# Hosted providers (Sarvam speech, the LLM) are set on the admin page at
# /settings once logged in with the token; they persist in the data volume.
# They can equally be set here and take effect on the next restart — see
# .env.example at the repository root for the names.
ENV
  chmod 600 .env
  echo "generated .env with a fresh API token"
fi

# The site block goes into the host Caddy through an import, so the other
# site's own blocks are never edited. Validate before reloading: a bad file
# on disk is harmless until Caddy reads it, and the reload is graceful.
sudo install -d -m 755 /etc/caddy/sites
sudo install -m 644 caddy-site.conf /etc/caddy/sites/samparkai.caddy
if ! sudo grep -qF 'import /etc/caddy/sites/*.caddy' /etc/caddy/Caddyfile; then
  printf '\n# Additional sites, one file each.\nimport /etc/caddy/sites/*.caddy\n' \
    | sudo tee -a /etc/caddy/Caddyfile >/dev/null
fi
sudo caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile >/dev/null
sudo systemctl reload caddy
echo "host Caddy reloaded with the samparkai site"

docker compose up -d --build
# The root disk here is small and shared; the build cache would otherwise
# grow by about a gigabyte per deploy. Rebuilds are a few minutes slower.
docker builder prune -f >/dev/null
docker compose ps

echo
for _ in $(seq 1 30); do
  if curl -fsS -o /dev/null http://127.0.0.1:8091/api/health; then
    echo "app healthy on 127.0.0.1:8091"; break
  fi
  sleep 2
done
echo
# Printed only on the run that generates it. Every later deploy echoed the
# token again, so a live credential accumulated in terminal scrollback, and
# in the log of anything that ran this, for a value that had not changed
# since the first deploy and is readable on the box by whoever can deploy.
if [ "$FRESH_TOKEN" = yes ]; then
  echo "API token, generated just now (also in deploy/samparkai/.env):"
  grep '^VAANI_API_TOKEN=' .env | cut -d= -f2-
else
  echo "API token unchanged. To read it on the box:"
  echo "  grep '^VAANI_API_TOKEN=' /opt/samparkai/deploy/samparkai/.env"
fi
echo
echo "Console: https://samparkai.demosites.co.in/  once DNS points at this box;"
echo "         Caddy fetches the certificate by itself when it does."
REMOTE
