#!/usr/bin/env bash
# Deploy SamparkAI to the AWS VM from a checkout on this machine.
#
#   deploy/samparkai/deploy.sh ubuntu@<ec2-address> [path/to/EuphoriaKey.pem]
#
# Ships exactly what is committed (git archive of HEAD: no venv, no data, no
# keys), generates deploy/samparkai/.env on the box with a fresh API token the
# first time, then builds and starts the stack. Re-running redeploys the
# current HEAD and keeps the existing .env and data volume.
set -euo pipefail

TARGET=${1:?usage: deploy.sh user@host [key.pem]}
KEY=${2:-EuphoriaKey.pem}
REMOTE_DIR=/opt/samparkai

cd "$(git rev-parse --show-toplevel)"
SSH=(ssh -i "$KEY" -o StrictHostKeyChecking=accept-new "$TARGET")

echo "==> preparing $REMOTE_DIR on $TARGET"
"${SSH[@]}" "sudo mkdir -p $REMOTE_DIR && sudo chown \"\$USER\" $REMOTE_DIR"

echo "==> shipping $(git rev-parse --short HEAD)"
git archive --format=tar HEAD | "${SSH[@]}" "tar -x -C $REMOTE_DIR"

echo "==> building and starting"
"${SSH[@]}" TARGET_HOST="${TARGET#*@}" bash -s <<'REMOTE'
set -euo pipefail
cd /opt/samparkai/deploy/samparkai

# The public address, for the bootstrap certificate Caddy serves on the bare
# IP until DNS points the domain here. IMDSv2 first; fall back to the address
# this deploy was aimed at.
IMDS_TOKEN=$(curl -sS -m 2 -X PUT http://169.254.169.254/latest/api/token \
             -H 'X-aws-ec2-metadata-token-ttl-seconds: 60' 2>/dev/null || true)
PUBLIC_IP=$(curl -sS -m 2 -H "X-aws-ec2-metadata-token: $IMDS_TOKEN" \
            http://169.254.169.254/latest/meta-data/public-ipv4 2>/dev/null || true)
PUBLIC_IP=${PUBLIC_IP:-$TARGET_HOST}

if [ ! -f .env ]; then
  TOKEN=$(python3 -c 'import secrets; print(secrets.token_urlsafe(32))' 2>/dev/null \
          || openssl rand -hex 32)
  cat > .env <<ENV
# Generated by deploy.sh. Runtime configuration for the SamparkAI container.
VAANI_ENV=prod
VAANI_API_TOKEN=$TOKEN
VAANI_LOG_LEVEL=INFO
PUBLIC_IP=$PUBLIC_IP
# Hosted providers (Sarvam speech, the LLM) are set on the admin page at
# /settings once logged in with the token; they persist in the data volume.
# They can equally be set here and take effect on the next restart — see
# .env.example at the repository root for the names.
ENV
  chmod 600 .env
  echo "generated .env with a fresh API token"
else
  # Keep the token; refresh the address in case the instance moved.
  grep -q '^PUBLIC_IP=' .env && sed -i "s/^PUBLIC_IP=.*/PUBLIC_IP=$PUBLIC_IP/" .env \
    || echo "PUBLIC_IP=$PUBLIC_IP" >> .env
fi

if docker compose version >/dev/null 2>&1; then DC="docker compose"; else DC="docker-compose"; fi
if ! docker info >/dev/null 2>&1; then DC="sudo $DC"; fi

$DC up -d --build
$DC ps
echo
echo "API token (also in /opt/samparkai/deploy/samparkai/.env):"
grep '^VAANI_API_TOKEN=' .env | cut -d= -f2-
echo
echo "Console: https://$PUBLIC_IP/  (accept the one-time certificate warning)"
echo "         https://samparkai.demosites.co.in/  once DNS points here"
REMOTE
